name: Build Forge 1.8.9 Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Upload Mod Jar
      uses: actions/upload-artifact@v4
      with:
        name: ForgeMod-Jar
        path: build/libs/*.jar
